<?php

return [
    'role_defaults' => [
        'admin' => [
            '*',
        ],
        'funcionario' => [
            'pdv.acessar',
            'pdv.vender',
            'pdv.zerar',
            'pdv.cadastro_rapido',
            'pdv.historico.visualizar',
            'caixa.turno.visualizar',
            'caixa.turno.abrir',
            'caixa.turno.movimentar',
            'caixa.fechamento.visualizar',
            'caixa.fechamento.gerenciar',
            'perfil.editar',
        ],
    ],

    'available' => [
        'dashboard.visualizar',
        'usuario.gerenciar',
        'produto.visualizar',
        'produto.criar',
        'produto.editar',
        'produto.excluir',
        'produto.importar',
        'produto.definir_preco',
        'estoque.visualizar',
        'estoque.movimentar',
        'pdv.acessar',
        'pdv.vender',
        'pdv.zerar',
        'pdv.cadastro_rapido',
        'pdv.historico.visualizar',
        'caixa.turno.visualizar',
        'caixa.turno.abrir',
        'caixa.turno.movimentar',
        'caixa.fechamento.visualizar',
        'caixa.fechamento.gerenciar',
        'auditoria.visualizar',
        'relatorios.visualizar',
        'configuracoes.editar',
        'api.tokens.gerenciar',
        'api.produtos.ler',
        'api.produtos.escrever',
        'api.vendas.ler',
        'api.vendas.escrever',
        'api.estoque.ajustar',
    ],
];
